In [1]:
import numpy as np
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components

In [2]:
embeddings = np.random.randn(10, 512).astype(np.float32)

In [5]:
"""
Matrix will look like this:
    0   1   2   3
0   1   1   0   0
1   1   1   1   0
2   0   1   1   1
3   0   0   1   1
"""

'\nMatrix will look like this:\n    0   1   2   3\n0   1   1   0   0\n1   1   1   1   0\n2   0   1   1   1\n3   0   0   1   1\n'

In [6]:
edges = set([
    (0, 0), (0, 1),
    (1, 0), (1, 1), (1, 2),
    (2, 1), (2, 2), (2, 3),
    (3, 2), (3, 3),
])
nbr_documents = 4
matrix_shape = (nbr_documents, nbr_documents)
rows, cols = zip(*edges)
sparse_mat = coo_matrix((np.ones(len(edges)), (rows, cols)), shape=matrix_shape)
nbr_clusters, cluster = connected_components(sparse_mat)
print(sparse_mat.todense(), "\n")
print(nbr_clusters, "\n", cluster)

[[1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]] 

1 
 [0 0 0 0]


Connected components ensures there is only 1 cluster per document.  It may create false positives, or call things similar that should not be, but the alternative is to allow documents to exist in multiple clusters. Connected components also acts as a safeguard against false negatives, because it links things that are just under the similarity threshold.